#!/usr/bin/env bash

pivxdl::getLatestVersionURL(){
	local url='https://github.com/PIVX-Project/PIVX/releases/latest'
	curl -Ls -o /dev/null -w "%{url_effective}" "$url"
}

pivxdl::getLatestVersion(){
	pivxdl::getLatestVersionURL | awk -F"/" '{ print $NF}'
}

pivxdl::getMajorVersion(){
	pivxdl::getLatestVersion | tr -d 'v' | awk -F'.' '{ print $1 }'
}

pivxdl::getMinorVersion(){
	pivxdl::getLatestVersion | tr -d 'v' | awk -F'.' '{ print $2 }'
}

pivxdl::getPatchVersion(){
	pivxdl::getPatchVersion | tr -d 'v' |  awk -F'.' '{ print $3 }'
}

pivxdl::urlPrefix() {
	local url_prefix
	url_prefix="pivx-$(pivxdl::getLatestVersion)-"
	echo "$url_prefix"
}

pivxdl::urlSuffix(){
	# Unknown == pivx-3.1.1.tar.gz
	os="$1"
	case "$os" in
	--arch64)
		echo 'aarch64-linux-gnu.tar.gz'
		;;
	--arm32)
		echo 'arm-linux-gnueabihf.tar.gz'
		;;
	--macOS-HighSierra)
		echo 'high-sierra-only.dmg'
		;;
	--linux32)
		echo 'i686-pc-linux-gnu.tar.gz'
		;;
	--linux64)
		echo 'x86_64-linux-gnu.tar.gz'
		;;
	--macOS-tarball)
		echo 'osx64.tar.gz'
		;;
	--MacOS-dmg)
		echo 'osx-unsigned.dmg'
		;;
	--win32-exe)
		echo 'win32-setup-unsigned.exe'
		;;
	--win32-zip)
		echo 'win32.zip'
		;;
	--win64-exe)
		echo 'win64-setup-unsigned.exe'
		;;
	--win64-zip)
		echo 'win64.zip'
		;;
	*)
		return 1
		;;
	esac		
}

pivxdl::urlBuilder(){
	local desired_os
	local url_root
	desired_os="$1"
	url_root='https://github.com/PIVX-Project/PIVX/releases/download'
	echo "${url_root}/$(pivxdl::getLatestVersion)/$(pivxdl::urlPrefix)$(pivxdl::urlSuffix "$desired_os")"
}


pivxdl::usage(){
	local script_name
	script_name="$(basename "$0")"
	echo "${script_name} (0.0.1) - A small CLI utility to grab the latest version of the PIVX wallet"
	echo ""
	echo "Usage: ${script_name} [--os-flag]"
	echo ""
	echo "Operating System Flags:"
	echo ""
	echo "  --arch64    | Arch 64-bit"
	echo "  --arm32     | Arm 32-bit"
	echo "  --linux32   | Linux 32-bit"
	echo "  --linux64   | Linux 64-bit"
	echo "  --MacOS-dmg | MacOS DMG"
	echo "  --macOS-tgz | MacOS Tarball"
	echo "  --macOS-HSO | MacOS High Sierra Only DMG"
	echo "  --win32-exe | Win32 Installer (Unsigned)"
	echo "  --win32-zip | Win32 Zip"
	echo "  --win64-exe | Win64 Installer (Unsigned)"
	echo "  --win64-zip | Win64 Zip"
	echo ""
	echo "Additional Flags:"
	echo ""
	echo "  --help      | Displays this output"
	echo ""
}

flag="$1"

if [ $# -eq 0 ]; then
	pivxdl::usage
	exit 1
fi

if ! pivxdl::urlSuffix "$flag" > /dev/null; then
	echo ""
	echo "ERROR: Unknown flag was passed. Pass --help to see available flags"
	echo ""
	exit 1
fi

case "$flag" in
	--help)
		pivxdl::usage
		;;
	*)
		pivxdl::urlBuilder "$flag"
		;;
esac

